export const SUB_CATEGORIES = ['PYQs', 'Syllabus', 'Assignments', 'Projects', 'Lecture Notes', 'Reference Books'];

export const INITIAL_RESOURCES: any[] = [];

export const College_COURSES = [
  'B.A. (Hons.) Economics',
  'B.A. (Hons.) English',
  'B.A. (Hons.) Geography',
  'B.A. (Hons.) Hindi',
  'B.A. (Hons.) History',
  'B.A. (Hons.) Philosophy',
  'B.A. (Hons.) Political Science',
  'B.A. (Hons.) Psychology',
  'B.A. (Hons.) Sanskrit',
  'B.A. (Hons.) Sociology',
  'B.A. Programme',
  'Master of Business Administration (MBA)',
  'B.Com. (Hons.)',
  'B.Com. Programme',
  'B.Sc. (Hons.) Anthropology',
  'B.Sc. (Hons.) Biological Sciences',
  'B.Sc. (Hons.) Biomedical Science',
  'B.Sc. (Hons.) Botany',
  'B.Sc. (Hons.) Chemistry',
  'B.Sc. (Hons.) Computer Science',
  'B.Sc. (Hons.) Electronics',
  'B.Sc. (Hons.) Food Technology',
  'B.Sc. (Hons.) Geology',
  'B.Sc. (Hons.) Instrumentation',
  'B.Sc. (Hons.) Mathematics',
  'B.Sc. (Hons.) Microbiology',
  'B.Sc. (Hons.) Physics',
  'B.Sc. (Hons.) Polymer Science',
  'B.Sc. (Hons.) Statistics',
  'B.Sc. (Hons.) Zoology',
  'B.Sc. Applied Physical Sciences',
  'B.Sc. Life Sciences',
  'B.Sc. Mathematical Sciences',
  'B.Sc. Physical Sciences',
  'B.Tech. (Information Technology and Mathematical Innovations)',
  'Bachelor of Management Studies (BMS)',
  'Bachelor of Business Administration (Financial Investment Analysis) [BBA(FIA)]',
  'B.A. (Hons.) Business Economics [BBE]',
  'Bachelor of Elementary Education (B.El.Ed.)',
  'Bachelor of Fine Arts (BFA)',
  'Ability Enhancement Course (AEC)',
  'Skill Enhancement Course (SEC)',
  'Value Addition Course (VAC)',

  // ── Delhi University Postgraduate (Master's) Courses ──
  'M.A. Economics',
  'M.A. English',
  'M.A. History',
  'M.A. Political Science',
  'M.A. Psychology',
  'M.A. Sociology',
  'M.A. Hindi',
  'M.A. Geography',
  'M.A. Sanskrit',
  'M.A. Philosophy',
  'M.Sc. Physics',
  'M.Sc. Chemistry',
  'M.Sc. Botany',
  'M.Sc. Zoology',
  'M.Sc. Mathematics',
  'M.Sc. Statistics',
  'M.Sc. Computer Science',
  'M.Sc. Microbiology',
  'M.Sc. Anthropology',
  'M.Sc. Geology',
  'Master of Commerce (M.Com.)',
  'Master of Computer Applications (MCA)',
  'Master of Laws (LL.M.)',
  'Bachelor of Laws (LL.B.)',
  'Master of Education (M.Ed.)',
  'Bachelor of Education (B.Ed.)',

  // ── Delhi University Ph.D. Courses ──
  'Ph.D. Economics',
  'Ph.D. English',
  'Ph.D. History',
  'Ph.D. Political Science',
  'Ph.D. Sociology',
  'Ph.D. Psychology',
  'Ph.D. Commerce',
  'Ph.D. Computer Science',
  'Ph.D. Physics',
  'Ph.D. Chemistry',
  'Ph.D. Mathematics',
  'Ph.D. Zoology',
  'Ph.D. Botany',
  'Ph.D. Law',
  'Ph.D. Geography',
  'Ph.D. Philosophy',
  'Ph.D. Sanskrit',
  'Ph.D. Urdu'
];

export const COURSE_METADATA: Record<string, { semesters: number; subCategories?: string[] }> = {
  'B.Sc. (Hons.) Mathematics': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs', 'Assignments'] },
  'B.Sc. (Hons.) Computer Science': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Projects', 'PYQs'] },
  'B.A. (Hons.) Economics': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Reference Books', 'PYQs'] },
  'B.Com. (Hons.)': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Financial Reports', 'PYQs'] },
  'B.Tech. (Information Technology and Mathematical Innovations)': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Engineering Drawings', 'PYQs'] },
  'B.A. Programme': { semesters: 6, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs'] },
  'B.Com. Programme': { semesters: 6, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs'] },
  
  'Master of Business Administration (MBA)': { 
    semesters: 4, 
    subCategories: [
      'Syllabus', 
      'Lecture Notes', 
      'PYQs', 
      'Assignments',
      'MBAFT-6101: Organizational Behavior',
      'MBAFT-6102: Data Analysis and Decision Tools',
      'MBAFT-6103: Managerial Economics',
      'MBAFT-6104: Accounting for Managers',
      'MBAFT-6105: Marketing Management',
      'MBAFT-6106: Human Resource Management',
      'MBAFT-6107: Business Communication',
      'MBAFT-6108: Information Technology Management',
      'MBAFT-6201: Organization Effectiveness and Change',
      'MBAFT-6202: Decision Modelling and Optimization',
      'MBAFT-6203: Economic Environment of Business',
      'MBAFT-6204: Corporate Finance',
      'MBAFT-6205: Management Accounting',
      'MBAFT-6206: Production and Operations Management',
      'MBAFT-6207: Marketing Research',
      'MBAFT-6208: Management of Information System',
      'MBAFT-6301: Business Ethics and Sustainability',
      'MBAFT-6302: Strategic Analysis',
      'MBAFT-6303: Project Study',
      'MBAFT-6401: Legal Environment of Business',
      'MBAFT-6402: Strategic Management',
      'MBAFT-6403: Global Business Management'
    ] 
  },

  // ── PG / Master's Courses metadata (4 semesters) ──
  'M.A. Economics': { semesters: 4 },
  'M.A. English': { semesters: 4 },
  'M.A. History': { semesters: 4 },
  'M.A. Political Science': { semesters: 4 },
  'M.A. Psychology': { semesters: 4 },
  'M.A. Sociology': { semesters: 4 },
  'M.A. Hindi': { semesters: 4 },
  'M.A. Geography': { semesters: 4 },
  'M.A. Sanskrit': { semesters: 4 },
  'M.A. Philosophy': { semesters: 4 },
  'M.Sc. Physics': { semesters: 4 },
  'M.Sc. Chemistry': { semesters: 4 },
  'M.Sc. Botany': { semesters: 4 },
  'M.Sc. Zoology': { semesters: 4 },
  'M.Sc. Mathematics': { semesters: 4 },
  'M.Sc. Statistics': { semesters: 4 },
  'M.Sc. Computer Science': { semesters: 4 },
  'M.Sc. Microbiology': { semesters: 4 },
  'M.Sc. Anthropology': { semesters: 4 },
  'M.Sc. Geology': { semesters: 4 },
  'Master of Commerce (M.Com.)': { semesters: 4 },
  'Master of Computer Applications (MCA)': { semesters: 4 },
  'Master of Laws (LL.M.)': { semesters: 4 },
  'Bachelor of Laws (LL.B.)': { semesters: 6 },
  'Master of Education (M.Ed.)': { semesters: 4 },
  'Bachelor of Education (B.Ed.)': { semesters: 4 },

  // ── Ph.D. Courses metadata (6 semesters) ──
  'Ph.D. Economics': { semesters: 6 },
  'Ph.D. English': { semesters: 6 },
  'Ph.D. History': { semesters: 6 },
  'Ph.D. Political Science': { semesters: 6 },
  'Ph.D. Sociology': { semesters: 6 },
  'Ph.D. Psychology': { semesters: 6 },
  'Ph.D. Commerce': { semesters: 6 },
  'Ph.D. Computer Science': { semesters: 6 },
  'Ph.D. Physics': { semesters: 6 },
  'Ph.D. Chemistry': { semesters: 6 },
  'Ph.D. Mathematics': { semesters: 6 },
  'Ph.D. Zoology': { semesters: 6 },
  'Ph.D. Botany': { semesters: 6 },
  'Ph.D. Law': { semesters: 6 },
  'Ph.D. Geography': { semesters: 6 },
  'Ph.D. Philosophy': { semesters: 6 },
  'Ph.D. Sanskrit': { semesters: 6 },
  'Ph.D. Urdu': { semesters: 6 }
};

export const EVENT_POSTERS: any[] = [];
