export const SUB_CATEGORIES = ['PYQs', 'Syllabus', 'Assignments', 'Projects', 'Lecture Notes', 'Reference Books'];

export const INITIAL_RESOURCES: any[] = [];

export const College_COURSES = [
  'B.A. (Hons.) Economics',
  'B.A. (Hons.) English',
  'B.A. (Hons.) Geography',
  'B.A. (Hons.) Hindi',
  'B.A. (Hons.) History',
  'B.A. (Hons.) Philosophy',
  'B.A. (Hons.) Political Science',
  'B.A. (Hons.) Psychology',
  'B.A. (Hons.) Sanskrit',
  'B.A. (Hons.) Sociology',
  'B.A. Programme',
  'Master of Business Administration (MBA)',
  'B.Com. (Hons.)',
  'B.Com. Programme',
  'B.Sc. (Hons.) Anthropology',
  'B.Sc. (Hons.) Biological Sciences',
  'B.Sc. (Hons.) Biomedical Science',
  'B.Sc. (Hons.) Botany',
  'B.Sc. (Hons.) Chemistry',
  'B.Sc. (Hons.) Computer Science',
  'B.Sc. (Hons.) Electronics',
  'B.Sc. (Hons.) Food Technology',
  'B.Sc. (Hons.) Geology',
  'B.Sc. (Hons.) Instrumentation',
  'B.Sc. (Hons.) Mathematics',
  'B.Sc. (Hons.) Microbiology',
  'B.Sc. (Hons.) Physics',
  'B.Sc. (Hons.) Polymer Science',
  'B.Sc. (Hons.) Statistics',
  'B.Sc. (Hons.) Zoology',
  'B.Sc. Applied Physical Sciences',
  'B.Sc. Life Sciences',
  'B.Sc. Mathematical Sciences',
  'B.Sc. Physical Sciences',
  'B.Tech. (Information Technology and Mathematical Innovations)',
  'Bachelor of Management Studies (BMS)',
  'Bachelor of Business Administration (Financial Investment Analysis) [BBA(FIA)]',
  'B.A. (Hons.) Business Economics [BBE]',
  'Bachelor of Elementary Education (B.El.Ed.)',
  'Bachelor of Fine Arts (BFA)'
];

export const COURSE_METADATA: Record<string, { semesters: number; subCategories?: string[] }> = {
  'B.Sc. (Hons.) Mathematics': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs', 'Assignments'] },
  'B.Sc. (Hons.) Computer Science': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Projects', 'PYQs'] },
  'B.A. (Hons.) Economics': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Reference Books', 'PYQs'] },
  'B.Com. (Hons.)': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Financial Reports', 'PYQs'] },
  'B.Tech. (Information Technology and Mathematical Innovations)': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Engineering Drawings', 'PYQs'] },
  'B.A. Programme': { semesters: 6, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs'] },
  'B.Com. Programme': { semesters: 6, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs'] },
  'Master of Business Administration (MBA)': { 
    semesters: 4, 
    subCategories: [
      'Syllabus', 
      'Lecture Notes', 
      'PYQs', 
      'Assignments',
      'MBAFT-6101: Organizational Behavior',
      'MBAFT-6102: Data Analysis and Decision Tools',
      'MBAFT-6103: Managerial Economics',
      'MBAFT-6104: Accounting for Managers',
      'MBAFT-6105: Marketing Management',
      'MBAFT-6106: Human Resource Management',
      'MBAFT-6107: Business Communication',
      'MBAFT-6108: Information Technology Management',
      'MBAFT-6201: Organization Effectiveness and Change',
      'MBAFT-6202: Decision Modelling and Optimization',
      'MBAFT-6203: Economic Environment of Business',
      'MBAFT-6204: Corporate Finance',
      'MBAFT-6205: Management Accounting',
      'MBAFT-6206: Production and Operations Management',
      'MBAFT-6207: Marketing Research',
      'MBAFT-6208: Management of Information System',
      'MBAFT-6301: Business Ethics and Sustainability',
      'MBAFT-6302: Strategic Analysis',
      'MBAFT-6303: Project Study',
      'MBAFT-6401: Legal Environment of Business',
      'MBAFT-6402: Strategic Management',
      'MBAFT-6403: Global Business Management'
    ] 
  },
};

export const EVENT_POSTERS: any[] = [];
