export const SUB_CATEGORIES = ['PYQs', 'Syllabus', 'Assignments', 'Projects', 'Lecture Notes', 'Reference Books'];

export const INITIAL_RESOURCES = [
  { 
    id: '1', 
    title: 'Calculus I Notes', 
    type: 'Note', 
    subCategory: 'Lecture Notes',
    course: 'B.Sc. (Hons.) Mathematics', 
    semester: 1, 
    tags: ['math', 'calculus', 'notes'],
    description: 'Comprehensive notes covering limits, continuity, derivatives, and their applications. Perfect for first-semester students.',
    link: 'https://example.com/calculus-notes.pdf',
    uploader: 'Aman Maurya',
    uploadDate: '2024-03-15',
    ratings: [5, 4, 5, 5, 4],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '2', 
    title: 'Microeconomics PYQ 2023', 
    type: 'PYQ', 
    subCategory: 'PYQs',
    course: 'B.A. (Hons.) Economics', 
    semester: 2, 
    tags: ['economics', 'pyq', '2023'],
    description: 'Previous year question paper for Microeconomics (2023). Includes questions on consumer theory and market structures.',
    link: 'https://example.com/micro-pyq.pdf',
    uploader: 'Rahul Sharma',
    uploadDate: '2024-01-20',
    ratings: [4, 3, 4, 5],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '3', 
    title: 'Data Structures Playlist', 
    type: 'Playlist', 
    subCategory: 'Lecture Notes',
    course: 'B.Sc. (Hons.) Computer Science', 
    semester: 3, 
    tags: ['cs', 'dsa', 'youtube'],
    description: 'A curated YouTube playlist covering arrays, linked lists, stacks, queues, and trees with practical implementations.',
    link: 'https://youtube.com/playlist?list=example',
    uploader: 'Priya Singh',
    uploadDate: '2023-11-10',
    ratings: [5, 5, 5, 4, 5],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '4', 
    title: 'Indian History: Medieval Period', 
    type: 'Note', 
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) History', 
    semester: 2, 
    tags: ['history', 'notes'],
    description: 'Detailed notes on the Delhi Sultanate, Mughal Empire, and socio-cultural developments in medieval India.',
    link: 'https://example.com/history-notes.pdf',
    uploader: 'Amit Kumar',
    uploadDate: '2024-02-05',
    ratings: [4, 4, 3, 4],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '5', 
    title: 'Organic Chemistry PYQ 2022', 
    type: 'PYQ', 
    subCategory: 'PYQs',
    course: 'B.Sc. (Hons.) Chemistry', 
    semester: 4, 
    tags: ['chemistry', 'pyq'],
    description: 'Previous year question paper for Organic Chemistry II (2022). Focuses on reaction mechanisms and spectroscopy.',
    link: 'https://example.com/chem-pyq.pdf',
    uploader: 'Sneha Gupta',
    uploadDate: '2023-12-25',
    ratings: [5, 4, 4],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '6', 
    title: 'Business Law Case Studies', 
    type: 'Note', 
    subCategory: 'Projects',
    course: 'B.Com. (Hons.)', 
    semester: 3, 
    tags: ['commerce', 'law'],
    description: 'A collection of important case studies for Business Law, including the Indian Contract Act and Sale of Goods Act.',
    link: 'https://example.com/law-cases.pdf',
    uploader: 'Vikram Singh',
    uploadDate: '2024-03-01',
    ratings: [3, 4, 4, 5, 3],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '7', 
    title: 'Quantum Mechanics Lectures', 
    type: 'Playlist', 
    subCategory: 'Lecture Notes',
    course: 'B.Sc. (Hons.) Physics', 
    semester: 5, 
    tags: ['physics', 'quantum'],
    description: 'Advanced lectures on wave mechanics, Schrödinger equation, and atomic structure from top university professors.',
    link: 'https://youtube.com/playlist?list=quantum',
    uploader: 'Dr. Rajesh',
    uploadDate: '2023-10-15',
    ratings: [5, 5, 4, 5],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '8', 
    title: 'English Literature: Romantic Era', 
    type: 'Note', 
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) English', 
    semester: 1, 
    tags: ['english', 'literature'],
    description: 'Notes on the works of Wordsworth, Coleridge, Keats, and Shelley, exploring themes of nature and imagination.',
    link: 'https://example.com/english-notes.pdf',
    uploader: 'Anjali Verma',
    uploadDate: '2024-01-10',
    ratings: [4, 5, 4, 4, 5],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '9', 
    title: 'Financial Accounting Full Course', 
    type: 'Playlist', 
    subCategory: 'Lecture Notes',
    course: 'B.Com. (Hons.)', 
    semester: 1, 
    tags: ['commerce', 'accounting', 'youtube'],
    description: 'Complete playlist for Financial Accounting covering journal entries, ledger, trial balance, and final accounts.',
    link: 'https://www.youtube.com/playlist?list=PLm_MSClsnwm8m_G_O_O_O_O_O',
    uploader: 'Commerce Hub',
    uploadDate: '2024-01-15',
    ratings: [5, 4, 5],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '10', 
    title: 'Political Theory: Concepts & Debates', 
    type: 'Playlist', 
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) Political Science', 
    semester: 1, 
    tags: ['polscience', 'theory', 'youtube'],
    description: 'Curated lectures on political theory, including liberty, equality, justice, and rights.',
    link: 'https://www.youtube.com/playlist?list=PLm_MSClsnwm9m_G_O_O_O_O_O',
    uploader: 'PolSci Academy',
    uploadDate: '2023-12-01',
    ratings: [4, 4, 5, 4],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '11', 
    title: 'Python for Data Science', 
    type: 'Playlist', 
    subCategory: 'Lecture Notes',
    course: 'B.Sc. (Hons.) Computer Science', 
    semester: 4, 
    tags: ['cs', 'python', 'data-science'],
    description: 'Learn Python programming with a focus on data analysis libraries like Pandas, NumPy, and Matplotlib.',
    link: 'https://www.youtube.com/playlist?list=PLm_MSClsnwm7m_G_O_O_O_O_O',
    uploader: 'Tech DU',
    uploadDate: '2024-02-20',
    ratings: [5, 5, 5, 5],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  { 
    id: '12', 
    title: 'Advanced Algorithms Book', 
    type: 'Book', 
    subCategory: 'Reference Books',
    course: 'B.Sc. (Hons.) Computer Science', 
    semester: 5, 
    tags: ['cs', 'algorithms', 'book'],
    description: 'A comprehensive reference book for advanced algorithms and complexity theory.',
    link: 'https://example.com/algorithms-book.pdf',
    directDownloadLink: 'https://example.com/algorithms-book.pdf',
    uploader: 'Admin',
    uploadDate: '2024-03-20',
    ratings: [5, 5],
    reports: [] as { reason: string, date: string }[],
    isApproved: true
  },
  // BBA (FIA) Resources
  {
    id: 'bba-fia-1',
    title: 'Financial Accounting and Analysis Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'Bachelor of Business Administration (Financial Investment Analysis) [BBA(FIA)]',
    semester: 1,
    tags: ['bba', 'fia', 'accounting'],
    description: 'Detailed notes on financial accounting principles and analysis for BBA(FIA) students.',
    link: 'https://example.com/bba-fia-accounting-notes',
    directDownloadLink: 'https://example.com/bba-fia-accounting-notes.pdf',
    uploader: 'SOL Faculty',
    uploadDate: '2024-03-22',
    ratings: [5, 5, 4],
    reports: [],
    isApproved: true
  },
  {
    id: 'bba-fia-2',
    title: 'Microeconomics PYQ 2024',
    type: 'PYQ',
    subCategory: 'PYQs',
    course: 'Bachelor of Business Administration (Financial Investment Analysis) [BBA(FIA)]',
    semester: 1,
    tags: ['bba', 'fia', 'economics', 'pyq'],
    description: 'Previous year question paper for Microeconomics (2024) for BBA(FIA).',
    link: 'https://example.com/bba-fia-micro-pyq',
    directDownloadLink: 'https://example.com/bba-fia-micro-pyq.pdf',
    uploader: 'Rahul Sharma',
    uploadDate: '2024-03-22',
    ratings: [4, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'bba-fia-3',
    title: 'Statistics for Business Decision Playlist',
    type: 'Playlist',
    subCategory: 'Lecture Notes',
    course: 'Bachelor of Business Administration (Financial Investment Analysis) [BBA(FIA)]',
    semester: 1,
    tags: ['bba', 'fia', 'statistics', 'youtube'],
    description: 'Curated YouTube playlist covering statistics for business decisions.',
    link: 'https://youtube.com/playlist?list=bba-fia-stats',
    uploader: 'EduTube',
    uploadDate: '2024-03-22',
    ratings: [5, 4, 5],
    reports: [],
    isApproved: true
  },
  // BMS Resources
  {
    id: 'bms-1',
    title: 'Fundamentals of Management Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'Bachelor of Management Studies (BMS)',
    semester: 1,
    tags: ['bms', 'management', 'notes'],
    description: 'Core concepts of management for BMS first semester.',
    link: 'https://example.com/bms-mgmt-notes',
    directDownloadLink: 'https://example.com/bms-mgmt-notes.pdf',
    uploader: 'SOL Admin',
    uploadDate: '2024-03-22',
    ratings: [5, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'bms-2',
    title: 'Principles of Marketing Playlist',
    type: 'Playlist',
    subCategory: 'Lecture Notes',
    course: 'Bachelor of Management Studies (BMS)',
    semester: 2,
    tags: ['bms', 'marketing', 'youtube'],
    description: 'Comprehensive marketing playlist for BMS students.',
    link: 'https://youtube.com/playlist?list=bms-marketing',
    uploader: 'Marketing Guru',
    uploadDate: '2024-03-22',
    ratings: [5, 5, 5],
    reports: [],
    isApproved: true
  },
  // B.A. (Hons.) Economics Resources
  {
    id: 'eco-hons-1',
    title: 'Introductory Mathematical Methods for Economics Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) Economics',
    semester: 1,
    tags: ['economics', 'math', 'notes'],
    description: 'Mathematical foundations for economic analysis.',
    link: 'https://example.com/eco-math-notes',
    directDownloadLink: 'https://example.com/eco-math-notes.pdf',
    uploader: 'Eco Scholar',
    uploadDate: '2024-03-22',
    ratings: [4, 4, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'eco-hons-2',
    title: 'Introductory Statistics for Economics PYQ',
    type: 'PYQ',
    subCategory: 'PYQs',
    course: 'B.A. (Hons.) Economics',
    semester: 1,
    tags: ['economics', 'statistics', 'pyq'],
    description: 'PYQ for Statistics for Economics.',
    link: 'https://example.com/eco-stats-pyq',
    directDownloadLink: 'https://example.com/eco-stats-pyq.pdf',
    uploader: 'Rahul Sharma',
    uploadDate: '2024-03-22',
    ratings: [5, 4],
    reports: [],
    isApproved: true
  },
  // B.A. (Hons.) English Resources
  {
    id: 'eng-hons-1',
    title: 'European Classical Literature Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) English',
    semester: 1,
    tags: ['english', 'literature', 'classical'],
    description: 'Notes on Homer, Sophocles, and other classical authors.',
    link: 'https://example.com/eng-classical-notes',
    directDownloadLink: 'https://example.com/eng-classical-notes.pdf',
    uploader: 'Lit Lover',
    uploadDate: '2024-03-22',
    ratings: [5, 5, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'eng-hons-2',
    title: '14th to 17th Century Poetry Playlist',
    type: 'Playlist',
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) English',
    semester: 2,
    tags: ['english', 'poetry', 'youtube'],
    description: 'Lectures on Chaucer, Spenser, and Milton.',
    link: 'https://youtube.com/playlist?list=eng-poetry',
    uploader: 'Poetry Hub',
    uploadDate: '2024-03-22',
    ratings: [4, 5, 4],
    reports: [],
    isApproved: true
  },
  // B.A. (Hons.) Political Science Resources
  {
    id: 'pol-hons-1',
    title: 'Understanding Political Theory Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) Political Science',
    semester: 1,
    tags: ['polscience', 'theory', 'notes'],
    description: 'Foundational concepts of political theory.',
    link: 'https://example.com/pol-theory-notes',
    directDownloadLink: 'https://example.com/pol-theory-notes.pdf',
    uploader: 'PolSci Pro',
    uploadDate: '2024-03-22',
    ratings: [5, 4, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'pol-hons-2',
    title: 'Colonialism and Nationalism in India PYQ',
    type: 'PYQ',
    subCategory: 'PYQs',
    course: 'B.A. (Hons.) Political Science',
    semester: 1,
    tags: ['polscience', 'history', 'india', 'pyq'],
    description: 'PYQ on the Indian national movement.',
    link: 'https://example.com/pol-india-pyq',
    directDownloadLink: 'https://example.com/pol-india-pyq.pdf',
    uploader: 'History Buff',
    uploadDate: '2024-03-22',
    ratings: [5, 5],
    reports: [],
    isApproved: true
  },
  // B.A. (Hons.) Psychology Resources
  {
    id: 'psy-hons-1',
    title: 'Introduction to Psychology Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) Psychology',
    semester: 1,
    tags: ['psychology', 'notes'],
    description: 'Introductory notes for psychology students.',
    link: 'https://example.com/psy-intro-notes',
    directDownloadLink: 'https://example.com/psy-intro-notes.pdf',
    uploader: 'Mind Explorer',
    uploadDate: '2024-03-22',
    ratings: [5, 5, 4],
    reports: [],
    isApproved: true
  },
  {
    id: 'psy-hons-2',
    title: 'Biopsychology Playlist',
    type: 'Playlist',
    subCategory: 'Lecture Notes',
    course: 'B.A. (Hons.) Psychology',
    semester: 1,
    tags: ['psychology', 'bio', 'youtube'],
    description: 'Lectures on the biological basis of behavior.',
    link: 'https://youtube.com/playlist?list=psy-bio',
    uploader: 'Neuro Science',
    uploadDate: '2024-03-22',
    ratings: [5, 5, 5],
    reports: [],
    isApproved: true
  },
  // B.Com. (Hons.) Resources
  {
    id: 'bcom-hons-1',
    title: 'Management Principles and Applications Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'B.Com. (Hons.)',
    semester: 1,
    tags: ['commerce', 'management', 'notes'],
    description: 'Management principles for B.Com. (Hons.).',
    link: 'https://example.com/bcom-mgmt-notes',
    directDownloadLink: 'https://example.com/bcom-mgmt-notes.pdf',
    uploader: 'Commerce Hub',
    uploadDate: '2024-03-22',
    ratings: [5, 4, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'bcom-hons-2',
    title: 'Corporate Accounting PYQ',
    type: 'PYQ',
    subCategory: 'PYQs',
    course: 'B.Com. (Hons.)',
    semester: 2,
    tags: ['commerce', 'accounting', 'pyq'],
    description: 'PYQ for Corporate Accounting.',
    link: 'https://example.com/bcom-corp-acc-pyq',
    directDownloadLink: 'https://example.com/bcom-corp-acc-pyq.pdf',
    uploader: 'Accountant',
    uploadDate: '2024-03-22',
    ratings: [5, 5],
    reports: [],
    isApproved: true
  },
  // B.A. Programme Resources
  {
    id: 'ba-prog-1',
    title: 'History of India from Earliest Times to 300 CE Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'B.A. Programme',
    semester: 1,
    tags: ['history', 'notes', 'ancient'],
    description: 'Comprehensive notes on ancient Indian history for B.A. Programme students.',
    link: 'https://example.com/ba-history-notes',
    directDownloadLink: 'https://example.com/ba-history-notes.pdf',
    uploader: 'History Buff',
    uploadDate: '2024-03-22',
    ratings: [5, 4],
    reports: [],
    isApproved: true
  },
  {
    id: 'ba-prog-2',
    title: 'Basic Concepts and Ideas in Education PYQ',
    type: 'PYQ',
    subCategory: 'PYQs',
    course: 'B.A. Programme',
    semester: 1,
    tags: ['education', 'pyq'],
    description: 'Previous year question paper for Education (Major/Minor) in B.A. Programme.',
    link: 'https://example.com/ba-edu-pyq',
    directDownloadLink: 'https://example.com/ba-edu-pyq.pdf',
    uploader: 'Edu Scholar',
    uploadDate: '2024-03-22',
    ratings: [5, 5],
    reports: [],
    isApproved: true
  },
  // MBA Resources
  {
    id: 'mba-1',
    title: 'MBAFT-6101: Organizational Behavior Notes',
    type: 'Note',
    subCategory: 'Lecture Notes',
    course: 'Master of Business Administration (MBA)',
    semester: 1,
    tags: ['mba', 'ob', 'notes'],
    description: 'Comprehensive notes for Organizational Behavior (MBAFT-6101). Covers individual behavior, group dynamics, and organizational culture.',
    link: 'https://example.com/mba-ob-notes',
    directDownloadLink: 'https://example.com/mba-ob-notes.pdf',
    uploader: 'MBA Hub',
    uploadDate: '2024-03-22',
    ratings: [5, 5, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'mba-2',
    title: 'MBAFT-6104: Accounting for Managers PYQ',
    type: 'PYQ',
    subCategory: 'PYQs',
    course: 'Master of Business Administration (MBA)',
    semester: 1,
    tags: ['mba', 'accounting', 'pyq'],
    description: 'Previous year question paper for Accounting for Managers (MBAFT-6104).',
    link: 'https://example.com/mba-accounting-pyq',
    directDownloadLink: 'https://example.com/mba-accounting-pyq.pdf',
    uploader: 'Finance Pro',
    uploadDate: '2024-03-22',
    ratings: [4, 5],
    reports: [],
    isApproved: true
  },
  {
    id: 'mba-3',
    title: 'MBAFT-6204: Corporate Finance Playlist',
    type: 'Playlist',
    subCategory: 'Lecture Notes',
    course: 'Master of Business Administration (MBA)',
    semester: 2,
    tags: ['mba', 'finance', 'youtube'],
    description: 'Curated playlist for Corporate Finance (MBAFT-6204). Covers capital budgeting, cost of capital, and working capital management.',
    link: 'https://youtube.com/playlist?list=mba-corp-finance',
    uploader: 'EduTube MBA',
    uploadDate: '2024-03-22',
    ratings: [5, 5],
    reports: [],
    isApproved: true
  }
];

export const DU_COURSES = [
  'B.A. (Hons.) Economics',
  'B.A. (Hons.) English',
  'B.A. (Hons.) Geography',
  'B.A. (Hons.) Hindi',
  'B.A. (Hons.) History',
  'B.A. (Hons.) Philosophy',
  'B.A. (Hons.) Political Science',
  'B.A. (Hons.) Psychology',
  'B.A. (Hons.) Sanskrit',
  'B.A. (Hons.) Sociology',
  'B.A. Programme',
  'Master of Business Administration (MBA)',
  'B.Com. (Hons.)',
  'B.Com. Programme',
  'B.Sc. (Hons.) Anthropology',
  'B.Sc. (Hons.) Biological Sciences',
  'B.Sc. (Hons.) Biomedical Science',
  'B.Sc. (Hons.) Botany',
  'B.Sc. (Hons.) Chemistry',
  'B.Sc. (Hons.) Computer Science',
  'B.Sc. (Hons.) Electronics',
  'B.Sc. (Hons.) Food Technology',
  'B.Sc. (Hons.) Geology',
  'B.Sc. (Hons.) Instrumentation',
  'B.Sc. (Hons.) Mathematics',
  'B.Sc. (Hons.) Microbiology',
  'B.Sc. (Hons.) Physics',
  'B.Sc. (Hons.) Polymer Science',
  'B.Sc. (Hons.) Statistics',
  'B.Sc. (Hons.) Zoology',
  'B.Sc. Applied Physical Sciences',
  'B.Sc. Life Sciences',
  'B.Sc. Mathematical Sciences',
  'B.Sc. Physical Sciences',
  'B.Tech. (Information Technology and Mathematical Innovations)',
  'Bachelor of Management Studies (BMS)',
  'Bachelor of Business Administration (Financial Investment Analysis) [BBA(FIA)]',
  'B.A. (Hons.) Business Economics [BBE]',
  'Bachelor of Elementary Education (B.El.Ed.)',
  'Bachelor of Fine Arts (BFA)'
];

export const COURSE_METADATA: Record<string, { semesters: number; subCategories?: string[] }> = {
  'B.Sc. (Hons.) Mathematics': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs', 'Assignments'] },
  'B.Sc. (Hons.) Computer Science': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Projects', 'PYQs'] },
  'B.A. (Hons.) Economics': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Reference Books', 'PYQs'] },
  'B.Com. (Hons.)': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Financial Reports', 'PYQs'] },
  'B.Tech. (Information Technology and Mathematical Innovations)': { semesters: 8, subCategories: ['Syllabus', 'Lecture Notes', 'Engineering Drawings', 'PYQs'] },
  'B.A. Programme': { semesters: 6, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs'] },
  'B.Com. Programme': { semesters: 6, subCategories: ['Syllabus', 'Lecture Notes', 'PYQs'] },
  'Master of Business Administration (MBA)': { 
    semesters: 4, 
    subCategories: [
      'Syllabus', 
      'Lecture Notes', 
      'PYQs', 
      'Assignments',
      'MBAFT-6101: Organizational Behavior',
      'MBAFT-6102: Data Analysis and Decision Tools',
      'MBAFT-6103: Managerial Economics',
      'MBAFT-6104: Accounting for Managers',
      'MBAFT-6105: Marketing Management',
      'MBAFT-6106: Human Resource Management',
      'MBAFT-6107: Business Communication',
      'MBAFT-6108: Information Technology Management',
      'MBAFT-6201: Organization Effectiveness and Change',
      'MBAFT-6202: Decision Modelling and Optimization',
      'MBAFT-6203: Economic Environment of Business',
      'MBAFT-6204: Corporate Finance',
      'MBAFT-6205: Management Accounting',
      'MBAFT-6206: Production and Operations Management',
      'MBAFT-6207: Marketing Research',
      'MBAFT-6208: Management of Information System',
      'MBAFT-6301: Business Ethics and Sustainability',
      'MBAFT-6302: Strategic Analysis',
      'MBAFT-6303: Project Study',
      'MBAFT-6401: Legal Environment of Business',
      'MBAFT-6402: Strategic Management',
      'MBAFT-6403: Global Business Management'
    ] 
  },
};

export const EVENT_POSTERS = [
  { id: 1, title: 'Antardhvani 2026', college: 'University of Delhi', image: 'https://picsum.photos/seed/du-fest/800/400', date: 'March 25-27' },
  { id: 2, title: 'Reverie 2026', college: 'Gargi College', image: 'https://picsum.photos/seed/gargi/800/400', date: 'March 28-30' },
  { id: 3, title: 'Nexus 2026', college: 'Sri Venkateswara College', image: 'https://picsum.photos/seed/venky/800/400', date: 'April 2-4' },
  { id: 4, title: 'Tarang 2026', college: 'LSR College', image: 'https://picsum.photos/seed/lsr/800/400', date: 'April 5-7' },
];
